### ISSUE TITLE
USER STORY: Anonymous feedback

### ISSUE THREAD

**Issue by AlexanderAberg** [AlexanderAberg/My-First-Agile-Project#6]
As a **role** I can **capability** so that **received benefit**

# **Acceptance Criteria:** &nbsp;
+ **Acceptance Criteria 1:** Be able to uncheck name
+ **Acceptance Criteria 2:** Be able to check it again.
+ **Acceptance Criteria 3:** Be able to use same functions as normal poll

# **Tasks** &nbsp;
- [ ] Create a check box for name
- [ ] Make sure the name still won't be registered
- [ ] Make it fit with the normal poll looks and functions
